### PR TITLE
Issue-33: build_file_line and build_syslog_frame call the __stdlog_pr…

### PR DESCRIPTION
**Pull request by dabright**
…int_\* functions incorrectly

Change these functions so that they call the __stdlog_print_\* functions with
the correct buffer size.

### CODE REVIEW

**Comment by dabright** [comment]
@rgerhards Any comments on this PR?

**Comment by rgerhards** [comment]
could you rebase this to current master?

**Comment by dabright** [comment]
Rebased.

**Comment by dabright** [comment]
Any update on this?

**Pull request merged**
