### PR TITLE
AIX Port for liblogging

### PR DESCRIPTION
**Pull request by purnimam1**
@rgerhards Please let me know if you have any comments

### CODE REVIEW

**Comment by purnimam1** [comment]
@rgerhards I believe freebsd failure is because of https://github.com/rsyslog/liblogging/pull/37 ?

**Comment by pduveau** [comment]
@purnimam1 I see that you proposed to use xlc. This version of the command do not defines correct macros for multithreading. We should use xlc_r instead.

**Comment by purnimam1** [comment]
@pduveau I do not see any pthread calls in the library as such, and to make sure thread safe routines from libc are used I have added THREAD_SAFE compiler flag. 
Am I missing something in liblogging design ?

**Comment by rgerhards** [comment]
@purnimam1 #37 is now merged, please rebase to master (git rebase is preferred over git merge).

**Comment by purnimam1** [comment]
@rgerhards let me know if this is how you expected me to rebase, since Im new to this.

**Comment by rgerhards** [comment]
@purnimam1 This looks like it was done with git merge vs. git rebase. To rebase, you first update your local master branch as follows:
```
$ git fetch official
$ git checkout master
$ git rebase official master
$ git push
````
Here, I assumed that you have added the official repository via ```git remote add official https://github.com/...```. Then, you can do the actual rebase to your feature branch:
```
$ git checkout <your-feature-branch>
$ git rebase
```
follow ```man git-rebase``` for the process.

Git merge also works, and sometimes is much easier to do. It's also OK to use a direct merge, but it makes the history ugly and it can lead to problems if you rewrite parts of the history that you have merged in.
HTH Rainer

**Pull request merged**
